### ISSUE TITLE
I am getting this error plz help me

### ISSUE THREAD

**Issue by swamy-m-s** [hacky1997/voice-based-email-for-blind#22]
Traceback (most recent call last):
  File "c:\Users\msswa\Desktop\Mini Project\voice-based-email-for-blind\voice_based_email_for_blind.py", line 104, in <module>
    mail.login('projectmini152@gmail.com','7760393981') #login part
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\smtplib.py", line 730, in login
    raise last_exception
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials j10sm5731558pfn.207 - gsmtp')
PS C:\Users\msswa\Desktop\Mini Project\voice-based-email-for-blind>

**Comment by hacky1997** [comment]
@swamy-m-s Please follow up documentation. I have already solved this issue before.
