### ISSUE TITLE
Error on sendmail

### ISSUE THREAD

**Issue by MoahmmedFahd** [hacky1997/voice-based-email-for-blind#23]
![Screenshot (83)_LI](https://user-images.githubusercontent.com/73108032/128005780-2135424b-bf81-4c5a-a78f-edcbe3d7120b.jpg)

Hello Sir , 

i have this issue please could you help me .

this is my code :

### mail = smtplib.SMTP('smtp.gmail.com',587)    #host and port area
    mail.ehlo()  #Hostname to send for this command defaults to the FQDN of the local host.
    mail.starttls() #security connection
    mail.login('hamzah20215@gmail.com','password') #login part
    mail.sendmail('emailID','victimID',msg) #send part
    print ("Congrates! Your mail has send. ")
    tts = gTTS(text="Congrates! Your mail has send. ", lang='en')
    ttsname=("send.mp3") #Example: path -> C:\Users\sayak\Desktop> just change with your desktop directory. Don't use my directory.
    tts.save(ttsname)
    music = pyglet.media.load(ttsname, streaming = False)

and this is the error : 

### You are logging from : moham
1. composed a mail.
2. Check your inbox
Your choice:
ok done!!
You said : 1
Your message :
ok done!!
You said : hi Mohammed
Traceback (most recent call last):
  File "C:/Users/moham/OneDrive/Desktop/voice-based-email-for-blind-master/voice_based_email_for_blind.py", line 105, in <module>
    mail.sendmail('emailID','victimID',msg) #send part
  File "C:\Python38\lib\smtplib.py", line 885, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'victimID': (553, b'5.1.3 The recipient address <victimID> is not a valid RFC-5321 address. e16sm14535363pja.14 - gsmtp')}

**Comment by the-horseman** [comment]
Hello,
Try changing the port that you are using.
I suggest using port 465.

**Comment by MoahmmedFahd** [comment]
still i get error says : 
### Traceback (most recent call last):
  File "C:/Users/moham/OneDrive/Desktop/voice-based-email-for-blind-master/voice_based_email_for_blind.py", line 101, in <module>
    mail = smtplib.SMTP('smtp.gmail.com',465)    #host and port area
  File "C:\Python38\lib\smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Python38\lib\smtplib.py", line 341, in connect
    (code, msg) = self.getreply()
  File "C:\Python38\lib\smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
